# Pre-commit hooks for Terraform
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Terraform formatting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        name: Terraform format
        description: Format Terraform files

      - id: terraform_validate
        name: Terraform validate
        description: Validate Terraform configuration
        args:
          - --hook-config=--retry-once-with-cleanup=true

      - id: terraform_docs
        name: Terraform docs
        description: Generate Terraform documentation
        args:
          - --args=--output-file=README.md
          - --args=--output-mode=inject

      - id: terraform_tflint
        name: TFLint
        description: Lint Terraform files with tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

      - id: terraform_tfsec
        name: TFSec
        description: Security scan with tfsec
        args:
          - --args=--soft-fail

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude: ^test/.*\.go$

      - id: end-of-file-fixer
        name: Fix end of files
        exclude: ^test/.*\.go$

      - id: check-yaml
        name: Check YAML files
        args: ['--safe']

      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']

      - id: check-merge-conflict
        name: Check for merge conflicts

      - id: mixed-line-ending
        name: Check line endings
        args: ['--fix=lf']

      - id: detect-private-key
        name: Detect private keys

  # Go formatting for tests
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: Format Go code
        files: ^test/.*\.go$

      - id: go-mod-tidy
        name: Tidy Go modules
        files: ^test/go\.(mod|sum)$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: Lint markdown files
        args: ['--fix', '--disable', 'MD013', 'MD033', 'MD041']
